### ISSUE TITLE
Patrick Curran matflow help

### ISSUE THREAD

**Issue by gcapes** [LightForm-group/non-repo-issues#24]
Meeting notes:
DefDap is a python package that measures displacement data linking to orientation data

- [x] The defdap matflow extension isn't (wasn't when he checked a few months ago) working in new matflow
      Patrick is going test a known working example of RVE extrusion (which takes ~24 hrs) using a new version of matflow, and would need help to get it working if it still isn't working
- [x] ~~difficult to access data from new matflow - unclear what the dictionary format is~~
    Since self-resolved. I demonstrated how to set a break point in pycharm to inspect variables as an approach to tackle this in future
- [ ] We had previously started working together on a graph plotting task schema - low priority but would like to finish this, and
- [ ] Learn how to write a new task schema (another vote for a tutorial)
- [ ] Patrick has already started (50%) writing documentation for how to use the RVE_extrusion schema, as the person who uses it most
- [ ] Patrick also suggested a group meeting for matflow 'stakeholders' to set priorities/gather documentation requirements around matflow

**Comment by gcapes** [comment]
@Patcurran 
The RVE extrusion example does run using the latest matflow, but runs out of memory. The workflow which used the old version of matflow targetted high memory nodes, but we can't figure out how to do this. @aplowman Could you rescue us please?

**Comment by gcapes** [comment]
Hi @aplowman 
Could you please advise on how to request specific resources?
The relevant section of the old workflow is
```
 - name: simulate_volume_element_loading
    method: CP_FFT
    software: DAMASK
    run_options:
      num_cores: 10
      l: mem256
      processing:
        num_cores: 4
        l: mem256
```

but I think @Patcurran has tried this with a new version of matflow and it doesn't work (is that correct?)

**Comment by gcapes** [comment]
There is another workflow affected by this same resources problem (this time mtex, trying to sample_texture from_CTF_file )

**Comment by gcapes** [comment]
It looks like you can request resources for the whole workflow with a top-level block like this, but this doesn't seem to work at the task level. Is it possible to do that?
```
resources:
  any:
    scheduler: sge
    scheduler_args:
      shebang_args: --login
      options: ["-l mem512"]
```
